Resume/urls.py
from  django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("philani", views.philani, name="philani"),
    path("lungas", views.lungas, name="lungas")
]

myportfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Resume/', include("Resume.urls")),
    path('tasks/', include("tasks.urls")),
    path('newyear/', include("newyear.urls"))
    
]


newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]



tasks/models.py
from django.db import models

# Create your models here.

Resume/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "Resume/index.html")

def philani(request):
    return HttpResponse("Hello Philani")

def lungas(request):
    return HttpResponse("Hello Lungas")

# def greet(request, name):
#     return HttpResponse(f"Hello, {name.capitalize()}!")

def greet(request, name):
    return render(request, "Resume/greet.html", {
        "name": name.capitalize()
    })

newyear/views.py
import datetime

from django.shortcuts import render

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day ==1
    })

tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

tasks = []

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10 )
# Create your views here.

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })
    
def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
            
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

Resume/templates/Resume/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resume</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

Resume/templates/Resume/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resume</title>
</head>
<body>
    <h1>Hello, world</h1>
</body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Year</title>
    <link href="{% static 'newyear/style.css' %}" rel="stylesheet">
</head>
<body>

    {% if newyear%}
    <h1>YES</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %}
</body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Add Task</h1>
<form action="{% url 'tasks:add' %}" method="post">
 {% csrf_token %}
  {{ form }}
  <input type="submit"/>
</form>
<a href="{% url 'tasks:index' %}"> View Tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %} 

{% block body %}
<h1>Tasks</h1>
<ul>
  {% for task in tasks %}
  <li>{{task}}</li>
  {% empty %}
  <li>No tasks.</li>
  {% endfor %}
</ul>
<a href="{% url 'tasks:add' %}"> Add Task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<DOCTYPE html>
    <html land="en">
      <head>
        <title>Tasks</title>
      </head>
      <body>
        {% block body %}
        {% endblock %}
      </body>
    </html>